import Head from "next/head";
import { Header } from "../components/Header";
import { ContactForm } from "../components/ContactForm";
import { Footer } from "../components/Footer";

export default function Home() {
  return (
    <div className="h-screen flex flex-col bg-[#47555E] bg-bottom bg-cover">
      <Head>
        <title>Charles Catin - Photographie | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed left-0 top-0 w-full h-full z-10 bg-gradient-to-t from-stone-700 to-[#47555E]"></div>
      <Header />
      <main className="h-full flex justify-center items-center z-20">
        <ContactForm />
      </main>
      <Footer />
    </div>
  );
}
