import Head from 'next/head'
import { Header } from '../components/header'
import {createClient} from 'contentful'
import PrestationsCard from '../components/prestationsCard'

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
  })
  const res = await client.getEntries({ content_type: 'prestations' })
  return {
    props: {
      prestations: res.items
    }
  }
}



export default function Home( {prestations}) {

  return (
    <div className="h-full flex flex-col bg-[#47555E]  bg-bottom bg-cover">
      <Head>
        <title>Charles Catin - Photographie | Prestations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className="h-full flex justify-center items-center z-20">
      <div className=' h-full flex flex-col items-center m-4 space-y-6'>
    <h1 className="mb-2 text-4xl font-bold tracking-tight text-cyan-200">Prestations et Tarifs</h1>
    <div className="h-full grid lg:grid-cols-2 gap-16 mb:gap-8">
    {prestations.map(prestation => (
            <PrestationsCard className="h-full" key={prestation.sys.id} prestation={prestation}/>
          ))}
      </div>
     </div>
         
        
         
              
      </main>
      <footer className="h-10 flex justify-center items-center z-20">
        <p>Charles Catin - Photographe</p>
      </footer>
    </div>
  )
}